name: workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # downloads a copy of repository
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Build
        run: mvn package -Dmaven.test.skip=true