name: workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # downloads a copy of repository
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Build
        run: mvn package -Dmaven.test.skip=true
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./target/site/jacoco/jacoco.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)